from PyQt6 import QtCore, QtGui, QtWidgets


class Main_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 472)
        Dialog.setMinimumSize(QtCore.QSize(360, 472))
        Dialog.setMaximumSize(QtCore.QSize(360, 472))
        Dialog.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 321, 301))
        self.textEdit.setObjectName("textEdit")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 331))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 350, 341, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(160, 20, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(160, 40, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(160, 60, 47, 13))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 440, 221, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox.raise_()
        self.textEdit.raise_()
        self.groupBox_2.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "))
        self.groupBox.setTitle(_translate("Dialog", "Keywords (DE/EN)"))
        self.groupBox_2.setTitle(_translate("Dialog", "Statistics"))
        self.label.setText(_translate("Dialog", "Total Generated Articles"))
        self.label_2.setText(_translate("Dialog", "Sleep Time (Seconds)"))
        self.label_3.setText(_translate("Dialog", "Preferred Language"))
        self.label_4.setText(_translate("Dialog", ":0"))
        self.label_5.setText(_translate("Dialog", ":0"))
        self.label_6.setText(_translate("Dialog", ":-"))
        self.pushButton.setText(_translate("Dialog", "Start Bot"))

